apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-secret.yaml
  - sc.yaml
  - create-dirs.yaml
  - mysql-pv.yaml
  - mysql-volume.yaml
  - mysql.yaml
  - mysql-service.yaml
  - wordpress-pv.yaml
  - wordpress-volume.yaml
  - wordpress.yaml
  - wordpress-service.yaml