apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: create-dir
spec:
  selector:
    matchLabels:
      app: create-dir
  template:
    metadata:
      labels:
        app: create-dir
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /mnt/data && sleep 3600"]
        volumeMounts:
        - mountPath: /mnt/data
          name: host-mnt
      volumes:
      - name: host-mnt
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate